### ISSUE TITLE
Avoiding obstcales

### ISSUE THREAD

**Issue by GoldenWings** [ogmacorp/EOgmaDrive#4]
Does the current configuration supports identifying and avoiding obstacles? or the model needs some sort of ultrasound sensors and lidars?

**Comment by 222464** [comment]
We do not have explicit object detection. Rather, one has to train the model (preferrably in real-time/online) to avoid obstacles by just not driving into them and by correcting mistakes if the model drives close to them on its own (when in prediction mode).
