### ISSUE TITLE
Toggling SDC mode after training causes car to move backwards (only)

### ISSUE THREAD

**Issue by aleonnet** [ogmacorp/EOgmaDrive#6]
Hi,
Great project! I've implemented everything just like the instructions.
The motorTest.py works very well and I don't even need to use the trimming adjust.

However when I run main.py (EOgmaNeo predictive hierarchy) to try the spin on the spot test as instructed and press the A button to toggle to SDC mode, it simply goes backwards all the way.

What could have possibly gone wrong?

Thank you.

Also the left and right variables on motorTest.py and main.py have different signs. If I use the as main.py the left/right is inverted.

motorTest.py:
left = min(1.0, max(-1.0, drive * 0.5 - drive * steer * 0.5))
right = min(1.0, max(-1.0, drive * 0.5 + drive * steer * 0.5))

main.py:
left = min(1.0, max(-1.0, drive * 0.5 + drive * steer * 0.5))
right = min(1.0, max(-1.0, drive * 0.5 - drive * steer * 0.5))

**Comment by 222464** [comment]
Hello!

Try flipping the signs for the left and right motors in the code. left and right are basically just the "tank-like" steering commands for the motors, derived from a the more natural "car-like" steering used by the controller.  It's possible that the motor signs are not set up correctly in the code right now. I'll take a look at it tomorrow!

For now, look for this code:

```
explorerhat.motor[0].speed(int(sendLeftMotor` * trimMulLeft * powerScalar * 100))
explorerhat.motor[1].speed(-int(sendRightMotor * trimMulRight * powerScalar * 100))
```
And try different signs in front of the int(...) part.

Let me know how it goes!

**Comment by aleonnet** [comment]
It worked, thank you!
I've inverted the signs of the code above, along with the previous change on the signs of 'left/sendLeftMotor' and 'right/sendRightMotor' formulas.
As a remark, I found it really difficult to control and train the model.
