### ISSUE TITLE
Configuration3 (uSDC)

### ISSUE THREAD

**Issue by Ola1234** [ogmacorp/EOgmaDrive#7]
So, im trying to make this car but i have a question, can i use other cameras? Like cheaper ones. If yes, can you link me? (~10$)

**Comment by 222464** [comment]
Hi,

Yes, you can use any camera compatible with the Pi Zero. I am not sure if there are any much cheaper than $20 though. Ideally it should be a wide-angle camera, like a fisheye camera.

**Comment by Ola1234** [comment]
@222464 ok, thanks for the response. 

Can It be these? https://m.banggood.com/en/1080P-5MP-160-Fish-Eye-Surveillance-Camera-Module-For-Raspberry-Pi-With-IR-Night-Vision-p-1234118.html?gmcCountry=BR&currency=BRL&cur_warehouse=CN&createTmp=1&utm_source=googleshopping&utm_medium=cpc_union&utm_content=2zou&utm_campaign=ssc-br-all&gclid=CjwKCAiAy-_iBRAaEiwAYhSlA-hACbaVCSm6UN1O0ZGZMAxEUxsN5Ao4mbqHhc-91jytd-XpERMwmBoCXkkQAvD_BwE

**Comment by 222464** [comment]
@Ola1234 Yes, that should work, it looks like the fisheye camera we used actually.

**Comment by Ola1234** [comment]
- @222464 Oh, Sorry for another question, but did i have to buy a steam controller? Because i have an chinese controller, like this one Dupad Story [2018 Updated] H9 2.4GHz Colorful Blacklit Mini Wireless Keyboard with Touchpad Mouse Combo, USB Rechargeable for Raspberry Pi,Google Android TV Box,HTPC,IPTV,PC,PAD,PS4 and More https://www.amazon.com/dp/B071FT92F8/ref=cm_sw_r_cp_apa_i_YikxCbMSG7B0X

**Comment by 222464** [comment]
@Ola1234 One of the reviews says that it worked for them on a Pi 3, so it will probably work here as well. Just make sure you get the proper adapter for the dongle (USB -> Micro USB).

**Comment by 222464** [comment]
@Ola1234 Oh, one thing I forgot to add: It seems that the controller you linked doesn't have an analog stick. This will make it more difficult to control the robot if you can only go full left/right or straight.
